name: WorldGenTesting
version: "1.0.0"
author: "MrKitty_Cat"
api-version: 1.20
main: dev.twelveoclock.worldgentesting.WorldGenTestingPlugin
load: STARTUP

commands:
  createWorld:
    usage: "/createWorld <worldName>"
    description: "Creates a new world with the given name"
  deleteWorld:
    usage: "/deleteWorld <worldName>"
    description: "Deletes a world with the given name"
  switchWorld:
    usage: "/switchWorld <worldName>"
    description: "Switches to the world with the given name"
